var teaLine = ['kalam','jamal','mal','rohim','korim','jim','sohid'];
var part= teaLine.slice(3,6);
console.log(part);
console.log(teaLine);
console.log(teaLine[0]);
console.log(teaLine[3]);
console.log(teaLine[7]);
var sonali= teaLine[5];
console.log(sonali);
var position= teaLine.indexOf('mal');
console.log(position);
var position= teaLine.indexOf('mala');
console.log(position);
teaLine.push('malan');
console.log(teaLine);
console.log(teaLine.length);
teaLine.pop();
console.log(teaLine);
teaLine.pop();
console.log(teaLine);

